### ISSUE TITLE
请教下，vue的项目怎么跑起来

### ISSUE THREAD

**Issue by 75509151** [iSk2y/vueshop#1]
大神，项目里面的 online-store如何运行啊，没有运行vue项目的经验。求指点，多谢啦！

为了跑这个vue项目，我安装了vue 2.9.6,想用webpack运行起来，
可是缺少package.json，好像因为某些东西的版本不对跑不起来。

大神，可以把webpack相关的配置也传下吗？ 或者写在博客里

**Comment by fj971706528** [comment]
cnpm install,执行这个命令，Vue框架会根据你项目中的package.json的配置文件安装node_modules依赖包。他这里的vue项目缺少的东西比较多，你可以先尝试下运行起来。有什么不清楚的可以加我git好友~~

**Comment by 75509151** [comment]
> cnpm install,执行这个命令，Vue框架会根据你项目中的package.json的配置文件安装node_modules依赖包。他这里的vue项目缺少的东西比较多，你可以先尝试下运行起来。有什么不清楚的可以加我git好友~~

我尝试过了，失主要是没有package.json,导致各种问题。根据提示信息处理后，还是有问题，估计是版本问题。

**Comment by fj971706528** [comment]
> > cnpm install,执行这个命令，Vue框架会根据你项目中的package.json的配置文件安装node_modules依赖包。他这里的vue项目缺少的东西比较多，你可以先尝试下运行起来。有什么不清楚的可以加我git好友~~
> 
> 我尝试过了，失主要是没有package.json,导致各种问题。根据提示信息处理后，还是有问题，估计是版本问题。

我这边前端的项目已经实现了，可能是这个远程库的package.json文件不全，你有需要我可以传一份vueshop前端的完整的项目给你

**Comment by 75509151** [comment]
> > > cnpm install,执行这个命令，Vue框架会根据你项目中的package.json的配置文件安装node_modules依赖包。他这里的vue项目缺少的东西比较多，你可以先尝试下运行起来。有什么不清楚的可以加我git好友~~
> > 
> > 
> > 我尝试过了，失主要是没有package.json,导致各种问题。根据提示信息处理后，还是有问题，估计是版本问题。
> 
> 我这边前端的项目已经实现了，可能是这个远程库的package.json文件不全，你有需要我可以传一份vueshop前端的完整的项目给你

**Comment by 75509151** [comment]
> > > cnpm install,执行这个命令，Vue框架会根据你项目中的package.json的配置文件安装node_modules依赖包。他这里的vue项目缺少的东西比较多，你可以先尝试下运行起来。有什么不清楚的可以加我git好友~~
> > 
> > 
> > 我尝试过了，失主要是没有package.json,导致各种问题。根据提示信息处理后，还是有问题，估计是版本问题。
> 
> 我这边前端的项目已经实现了，可能是这个远程库的package.json文件不全，你有需要我可以传一份vueshop前端的完整的项目给你

大神，加我下微信 18039090553
